### ISSUE TITLE
Begin Literature Review Rough Draft

### ISSUE THREAD

**Issue by gavinjalberghini** [JasonDCox/ML-Mentorship-GovSchool#15]
Description: For your literature review rough drafts, I would like you both to use overleaf (https://www.overleaf.com/) to write the document.  Please follow the IEEE format provided here: https://www.overleaf.com/latex/templates/ieee-conference-template/grfzhhncsfqn. 

Your paper should consist of the items in bold (non-bold items will be added in additional tickets): 
**- An introduction and background that discusses uses of the Nvidia Jetson in literature and software from your various sources. It should be relevant to the project you wish to solve.**
- A societal and engineering problem statement.
- A methodology of how your software solves the purposed problems.
- An analysis of the quality of your software.
- Conclusions on the performance of your software.

The goal is to have overlap between our weekly tasks and what you are assigned from the Governor's school. 

Acceptance Criteria: A individual pdf document is uploaded to GitHub as rough_draft.pdf. If the school allows you may do a combined submission. It must follow the provided format and contain at minimum 5 references to other research/articles using the Nvidia Jetson. Feel free to use papers I reference or ones you find yourself. 

Some Papers:
- https://www.sciencedirect.com/science/article/pii/S1383762118306404?casa_token=DehRIdQ9ZP4AAAAA:Wm13IfX7N1_5bfVTJyeRkrr1KKQnPtR593LleEx52Btp5rBpzTu4I5pP_l0XnLvsRTWXDq4Z
- https://www.sciencedirect.com/science/article/pii/S0263224119302489?casa_token=Aepr0C90IHUAAAAA:wZkSdOGSBek8aaJNFlZwEhCFU15IY9PRvOWeqAeL1aIUWj0AlH9Mcvw643bMElL-Pj1rEjiU
- https://link.springer.com/chapter/10.1007/978-3-319-64203-1_7
- https://ieeexplore.ieee.org/abstract/document/8870936?casa_token=QinVLdW_9VwAAAAA:-VBMrphuI7uHFTzvaXOV8QtGlxWhtrMhQP3HBgjX4xvjDX4kn4oKwIw0xNPkkhwWye-h8MaU
- https://ieeexplore.ieee.org/abstract/document/8760027?casa_token=ISmXDaOUUekAAAAA:fOxGQhkZ4WlQ6MVFUWLkLA9prosDwsl4MLc5956uA2BxeRV26jq_4fmjbkhTaD0SEo1SFqVB

References:
How to use overleaf: https://www.overleaf.com/learn/how-to/How_do_I_use_Overleaf%3F
How to use overleaf: https://www.youtube.com/watch?v=g8Ejj0T0yG4
SciHub: https://sci-hubtw.hkvisa.net/

**Comment by brandonC1234** [comment]
Done, but could use some work - Brandon

**Comment by JasonDCox** [comment]
Complete - Jason
