### ISSUE TITLE
Flush Out Ideas for Possible Jetson Projects

### ISSUE THREAD

**Issue by gavinjalberghini** [JasonDCox/ML-Mentorship-GovSchool#16]
Acceptance Criteria: Upload a markdown document named <your_name_dir>/project_ideas.md that contains the following:
- Three possible project ideas
- The hardware requirements for your project ideas (What sensors need to be accompanying the Jetson?)
- The software requirements for your project ideas (What software does the Jetson need to run?)
- Any relevant literature for the problem space of your proposal (i.e. robotic vision, classification, facial recognition, object detection, etc...)

Be prepared to debate and discuss at the next sprint review.

**Comment by brandonC1234** [comment]
Complete - Brandon
