### ISSUE TITLE
Configure Nvidia Jetson

### ISSUE THREAD

**Issue by gavinjalberghini** [JasonDCox/ML-Mentorship-GovSchool#17]
Description: This ticket is meant to be used to establish your working environment on the Nvidia Jetson. Use the Nvidia Jetson Tutorial listed below for assistance. 

Jetson Get Started Guide: https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#intro 
Jetson Developers Guide: https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#next

NOTE: When I went through this I did have to restart the Jetson. The first boot brought me to a black terminal, wait for a moment for the output to stop then restart your device if necessary. You should then get to a setup screen that should be very similar to the Ubuntu VM. You will need to plug a mouse and keyboard into the Jetson. 

Acceptance Criteria: 
- You have flashed your MicroSD card with the correct image specified in the guide. 
- You set up your device in 'display attached' mode.
- You created a user on your device. 
- You installed/configured git.

**Comment by gavinjalberghini** [comment]
https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-2gb-devkit#write

**Comment by JasonDCox** [comment]
Complete - Jason

**Comment by brandonC1234** [comment]
Complete - Brandon
