### ISSUE TITLE
Intro to Heterogeneous Programming Concepts

### ISSUE THREAD

**Issue by gavinjalberghini** [JasonDCox/ML-Mentorship-GovSchool#18]
Description: Many packages you plan to use will take advantage of the GPU processors on the Jetson. I want you to read the article below to see what kinds of software are typically paired with heterogeneous computing. 

Acceptance Criteria: Read the article posted at http://faculty.smu.edu/csc/workshops/2018/summer/hpc/session_17.html

**Comment by brandonC1234** [comment]
Complete - Brandon

**Comment by JasonDCox** [comment]
Complete - Jason
