### ISSUE TITLE
Create General outline for tickets

### ISSUE THREAD

**Issue by brandonC1234** [JasonDCox/ML-Mentorship-GovSchool#21]
Description: This ticket is meant to be used establish a general outline for us to write future tickets. instead of commenting on the ticket, we should edit on it.

Ticket outline:
1. Initialization
    a. Creating a social and engineering problem statement
    b. Define minimum viable product (including list of animals to identify)
    c. Decide on standard repo documentation
    d. Test performance and compatibility of NVIDIA Jetson on Tensorflow/Google CNN model for animal detection
2. Begin algorithm
    a. Write out software requirements (depends on 1.d)
    b. Gather dataset of pictures
    c. Train and test algorithm on computers (doesn't have to use GPU if that is too difficult)
3. Begin First Prototype (animal detection)
    a. Create initial outline for solution that includes software/hardware technologies
    b. Design case in solid works and 3d print it
    c. Transfer trained model to NVIDIA Jetson
    d.  Setup initial notification system
    f. Test Prototype
4. Design further (TBD)
    a. 

5. Final
    a. Create final outline for solution that includes software/hardware technologies

**Comment by gavinjalberghini** [comment]
Please write these tickets then close this one.

**Comment by gavinjalberghini** [comment]
Closing this issue so there is no confusion in the remaining tickets.
