### ISSUE TITLE
Readme, problem statement, minimum viable product

### ISSUE THREAD

**Issue by brandonC1234** [JasonDCox/ML-Mentorship-GovSchool#22]
## Description:
Define the problem in terms of engineering (technical) and social (how it benefits people)

## Acceptance Criteria:
 - Create a main read me to put these in
 - Create a social and engineering problem statement
 - Define minimum viable product (including list of animals to identify)
     - what is the minimum to say we were successful
 - Define the purpose of the repository
 - Define how the repository is organized 

## External References
 - engineering problem statement: https://examples.yourdictionary.com/problem-statement-examples.html

**Comment by gavinjalberghini** [comment]
README should additionally include the following:
- Define the purpose of the repository. Is it for specific application code? Will you include experimental results here? The final paper? 
- Define how the repository is organized. Where is the main source code? What is in each folder? Where could someone see how to use your application?
- A clear social and engineering problem statement. I feel that you have the social one complete, but you need to include a more technical problem statement for the engineering problem. Something along the lines of 'The proposed engineering problem is combining low power AI/ML solutions with miniature, cost-effective resources. Combining GUI, AI/ML, and Electrical engineering components into a finalized product.'

**Comment by gavinjalberghini** [comment]
Expect to define MVP on Jan 3rd.
