### ISSUE TITLE
Preliminary Test of Model and Data Options

### ISSUE THREAD

**Issue by brandonC1234** [JasonDCox/ML-Mentorship-GovSchool#24]
## Description:
Research different model options for the Nvidia Jetson Nano and create an initial implementation to generally test their performance

## Acceptance Criteria:
 - Come up with at least 3 different models
   - What are their benefits?
   - Have they been used on Jetson? (If so, link)
   - How easy to train and deploy?
   
 - Come up with potential data sources
   - Dog/Pet database?
   - Security camera footage?
   
 Note: Models should be utilizing the GPU

## External References:
General model stats: https://developer.nvidia.com/embedded/jetson-nano-dl-inference-benchmarks

**Comment by gavinjalberghini** [comment]
Please report your findings here once you have them.

**Comment by brandonC1234** [comment]
Was not able to get tensorflow to work, so I'm going to switch to Tensorflow RT, which seems to be preferred on the Jetson anyway

**Comment by gavinjalberghini** [comment]
I will add additional information about YOLO and its uses for the Nvidia Jetson.

**Comment by gavinjalberghini** [comment]
You Only Look Once (YOLO) Object Detection Algorithm 

Primary - https://pjreddie.com/darknet/yolo/
YOLOv3 Paper - https://pjreddie.com/media/files/papers/YOLOv3.pdf
YOLO version comparison video - https://www.youtube.com/watch?v=bsv28PuKiIM
Installation tutorial - https://www.youtube.com/watch?v=K03WZyee6ig&t=89s
Train YOLOv4 tiny on custom data - https://www.youtube.com/watch?v=NTnZgLsk_DA
YOLO vs YOLOv4 Tiny - https://medium.com/analytics-vidhya/yolov4-vs-yolov4-tiny-97932b6ec8ec
YOLOv4 Tiny trained on Google Collab - https://medium.com/analytics-vidhya/train-a-custom-yolov4-tiny-object-detector-using-google-colab-b58be08c9593

**Comment by brandonC1234** [comment]
## TensorFlow's ssd_mobilenet_v2

I followed through this [video](https://youtu.be/yqkISICHH-U), which provided a github repo that walked me through the initialization phase of tensorflow, which involved ensuring all modules were installed correctly, installing CUDA and cuDNN, and working through any errors (since tensorflow can mess up installing itself without reporting an error).

The video then went through how to take pictures and label them using libraries from openCV. He provided premade python programs that automatically arranged the folders and converted the annotated images into useable input for the TensorFlow model.

I completed the hand detection section of the video. Overall, I was able to achieve a decent accuracy (I only have 5 images per class), but it gave a good amount of false positives. 

My next step is to take pictures of my dogs' faces and see how well the algorithm detects them. I will have the results of that tomorrow.
