### ISSUE TITLE
Implement Repository Formatting

### ISSUE THREAD

**Issue by JasonDCox** [JasonDCox/ML-Mentorship-GovSchool#25]
# Description 

Take decision from the #23 ticket and implement the formatting that we chose. 

# Acceptance Criteria 

- Creates file folders and sorts files
- Mirrors the Newport News Climate Change repository 
- Clean irrelevant files or move them to a misc folder

# Reference 
https://github.com/gavinjalberghini/NNSB-CCIPT

**Comment by gavinjalberghini** [comment]
Let's clean irrelevant files or move them to a misc folder.
