### ISSUE TITLE
Decide on Comparable Dataset and Test/Train Split

### ISSUE THREAD

**Issue by JasonDCox** [JasonDCox/ML-Mentorship-GovSchool#31]
## Description 
Decide on a dataset to train and implement onto the Jetsons as well as the train/test split. Decide on metrics to test by. 

## Acceptance Criteria 
- Find a way to have the same pictures for test-train split in formats for both YOLO and Tensorflow
- Get metric output from algorithms with common dataset. ex. runtime, accuracy. 

## Idea
- https://public.roboflow.com/object-detection/oxford-pets/2

**Comment by brandonC1234** [comment]
## Dataset
For the general dog breeds, we will be using the by-species version of the Oxford pet dataset, found [here](https://public.roboflow.com/object-detection/oxford-pets/2)

For the specific dog, we will share identical pictures (found in the dataset folder of the GitHub) and annotate them for the algorithms.

## Metrics
For this project, we will focus on FPS, GPU usage, CPU usage, memory usage, average precision, and mean average precision

GPU usage, CPU usage, and memory usage will be gathered using [tegra-stats](https://docs.nvidia.com/drive/drive_os_5.1.6.1L/nvvib_docs/index.html#page/DRIVE_OS_Linux_SDK_Development_Guide/Utilities/util_tegrastats.html)
