### ISSUE TITLE
Write Conclusions

### ISSUE THREAD

**Issue by gavinjalberghini** [JasonDCox/ML-Mentorship-GovSchool#37]
Due March 7th

Acceptance Criteria:
- Write the conclusions portion of the paper.

**Comment by brandonC1234** [comment]
Written Conclusion:

As the results show, tensorRT and YOLO can both provide adequate performance for computer vision on the NVIDIA Jetson 
Nano, however, we found that YOLO development was easier for beginners compared to Tensorflow. While tfLite does set aside 
resources that could be used for other tasks in an application, it’s performance and lack of GPU utilization makes it 
unsatisfactory unless the application specifically needs it. In all, this application of a pet doorbell system is very feasible on the 
NVIDIA Jetson with both Tensorflow’s tensorRT and YOLO’s Tinyv4 algorithms providing adequate speed and accuracy for the 
task.
