### ISSUE TITLE
Write the Abstract

### ISSUE THREAD

**Issue by gavinjalberghini** [JasonDCox/ML-Mentorship-GovSchool#38]
Due March 14th

Acceptance Criteria:
- Write the abstract of the paper.

**Comment by brandonC1234** [comment]
Written Abstract:

Embedded computing devices have emerged as a cost-effective way of implementing machine learning on a mobile 
platform for use in everyday life. This research compares multiple implementations of convolutional neural networks on the 
Nvidia Jetson Nano for the purpose of animal recognition. We ultimately compare the use of a YOLOv4-tiny algorithm with 
optimized Tensorflow implementations to both demonstrate the capability of this technology for this application as well as 
determine which of the two prominent approaches would work better in this scenario. Both algorithms are evaluated on a set 
of incoming still images for metrics as well as tested with real-time footage to determine successful recognition ability. We 
found that animal detection and identification is very much achievable on the NVIDIA Jetson with a satisfactory frame rate, 
supporting our hypothesis that there are affordable computing solutions in this domain. Though both algorithms produced 
viable results, we found that certain constraints change which algorithm would be desired in this context.
