### ISSUE TITLE
Finalize the Research Paper

### ISSUE THREAD

**Issue by gavinjalberghini** [JasonDCox/ML-Mentorship-GovSchool#39]
Due March 21st

Acceptance Criteria:
- Complete and review all portions of the research paper.

**Comment by brandonC1234** [comment]
Paper has been finalized and converted to iEEE format with overleaf. The pdf version was uploaded to the github as [IEEE_paper.pdf](https://github.com/JasonDCox/ML-Mentorship-GovSchool/blob/main/IEEE_paper.pdf)
