### ISSUE TITLE
Create PPT Presentation Slides for MITRE Demonstration

### ISSUE THREAD

**Issue by gavinjalberghini** [JasonDCox/ML-Mentorship-GovSchool#40]
Description: I would like the two of you to present to the MITRE Hampton Roads site. This can be in person or virtual, though I would STRONGLY recommend it in person. 

Acceptance Criteria: Create a PowerPoint that follows the flow of your research paper. Use #20 as a reference for content.

**Comment by brandonC1234** [comment]
The more detailed presentation for MITRE has been finished and uploaded as a pdf to the github under the name "FInal_Presentation.pdf"
