### ISSUE TITLE
Refine Problem Statement/MVP with Deadline Considerations

### ISSUE THREAD

**Issue by gavinjalberghini** [JasonDCox/ML-Mentorship-GovSchool#45]
Description: Given the amount of time we have left for the mentorship I think we need to revisit the deliverables that we want. Personally, I think the task of Object Recognition is more valuable than writing an application layer over your existing code. We should potentially change the verbiage in our documents to reflect that we are fulfilling only the AI/ML technical requirements for this problem space. I am open to input here.

Acceptance Criteria:
- Project deliverables are decided for the end of the mentorship.

**Comment by brandonC1234** [comment]
Problem statement and minimum viable product have both been updated on the main GitHub readme file.

## Problem Statements

### Societal:
A pet can approach the door to their home and be let in automatically. Currently, facial recognition is used for humans to access things such as their phones or open locks but this is not widely implemented in the same sense for animals and the most common solution to allowing free entry of pets is an unlockable door to the home. Most pets now have to rely on the attention and availability of busy owners to let them out of possibly harsh conditions or face a security hazard with something like a conventional dog door. To avoid this, we plan to use the NVIDIA Jetson nano with software designed to automatically recognize a pet that matches what the user inputted into the program and unlock the door. This way, a user can add or remove pets and the door will only open to let in that specific pet. 

### Engineering
The proposed engineering problem is combining low power artificial intelligence/machine learning solutions with miniature, cost-effective resources. We will be investigating multiple approaches to the problem to gather results showing what would be most beneficial for the end user in future development of a physical product. 

## Minimum Viable Product
Process of experimental testing in which we are able to read in and train an algorithm on custom created datasets, and then detect a specific pet, with high accuracy, in future demonstrations. This process should be able to eventually be implemented in a control system.
