### ISSUE TITLE
Example Videos

### ISSUE THREAD

**Issue by JasonDCox** [JasonDCox/ML-Mentorship-GovSchool#46]
## Description 
A video will be uploaded that can be used to demonstrate how the Tensorflow and YOLO algorithms would work in reality. This will be the same video for both methods.

## Acceptance Criteria 
- Annotated video that can be used to demonstrate the process of detection in the hypothetical final product and compare between YOLO and Tensorflow

**Comment by brandonC1234** [comment]
Test videos have been uploaded for all algorithms.

The YOLO test video is in the YOLO folder.

The test videos for each Tensorflow module is in their respective folders in the metrics_results folder
